name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    paths:
      - 'frontend/**'

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint the code
        run: npm run lint
        continue-on-error: false

      - name: Build the frontend
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SEND_A_SECRET }}
          projectId: send-a-secret
          entryPoint: frontend/firebase.json
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
